import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// Importamos los estilos globales de la aplicación
import "./globals.css";
// Un componente personalizado para la barra lateral
import Sidebar from "@/components/Sidebar";

// Configuración de fuentes optimizadas usando next/font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Estos metadatos se inyectan en la etiqueta <head> del HTML. Son clave para el SEO.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout es el "Layout Principal" o "Plantilla Base" de Next.js (App Router).
 * Todo lo que pongas aquí envolverá a TODAS las páginas de tu aplicación.
 * En Next.js, el archivo layout.tsx es obligatorio en la raíz de la carpeta 'app'.
 */
export default function RootLayout({
  children, // 'children' será el contenido de la página actual que el usuario esté visitando
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Es obligatorio incluir las etiquetas <html> y <body> en el RootLayout
    // Usamos suppressHydrationWarning para evitar errores locos si el usuario
    // tiene extensiones como Dark Reader o Grammarly que inyectan código en el HTML inicial.
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen`}
      >
        {/* El Sidebar (Barra Lateral) aparecerá en todas las páginas porque está en el RootLayout */}
        <Sidebar />
        {/* Aquí se inyecta y renderiza el contenido de cada página específica */}
        <main className="flex-1 p-8">{children}</main>
      </body>
    </html>
  );
}
